name: Terraform Multi Environment Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - qa
          - prod

      action:
        description: "Terraform Action"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terrafrom-infra

    steps:

      # ==================================================
      # Checkout Repository
      # ==================================================

      - name: Checkout Code
        uses: actions/checkout@v4

      # ==================================================
      # Setup Terraform
      # ==================================================

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # ==================================================
      # Configure AWS Credentials
      # ==================================================

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # ==================================================
      # Terraform Init
      # ==================================================

      - name: Terraform Init
        run: |
          terraform init \
          -backend-config="environments/${{ github.event.inputs.environment }}/backend.hcl" \
          -reconfigure
      # ==================================================
      # Terraform Validate
      # ==================================================

      - name: Terraform Validate
        run: terraform validate

      # ==================================================
      # Terraform Format Check
      # ==================================================

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # ==================================================
      # Terraform Plan
      # ==================================================

      - name: Terraform Plan
        if: github.event.inputs.action == 'plan'
        run: |
          terraform plan \
          -var-file="environments/${{ github.event.inputs.environment }}/terraform.tfvars"

      # ==================================================
      # Terraform Apply
      # ==================================================

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        run: |
          terraform apply -auto-approve \
          -var-file="environments/${{ github.event.inputs.environment }}/terraform.tfvars"

      # ==================================================
      # Terraform Destroy
      # ==================================================

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: |
          terraform destroy -auto-approve \
          -var-file="environments/${{ github.event.inputs.environment }}/terraform.tfvars"